<?php
/**
 * CancelProvisionedSubscriptionDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\ProvisionerApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yoast.com provisioning API
 *
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yoast\ProvisionerApiClient;

/**
 * CancelProvisionedSubscriptionDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CancelProvisionedSubscriptionDto
 * @package     Yoast\ProvisionerApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CancelProvisionedSubscriptionDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CancelProvisionedSubscriptionDto"
     */
    public function testCancelProvisionedSubscriptionDto()
    {
    }

    /**
     * Test attribute "immediately"
     */
    public function testPropertyImmediately()
    {
    }
}
