<?php
/**
 * CreateProvisionedSubscriptionDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\ProvisionerApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yoast.com provisioning API
 *
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yoast\ProvisionerApiClient;

use PHPUnit\Framework\TestCase;

/**
 * CreateProvisionedSubscriptionDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CreateProvisionedSubscriptionDto
 * @package     Yoast\ProvisionerApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateProvisionedSubscriptionDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateProvisionedSubscriptionDto"
     */
    public function testCreateProvisionedSubscriptionDto()
    {
    }

    /**
     * Test attribute "customerEmail"
     */
    public function testPropertyCustomerEmail()
    {
    }

    /**
     * Test attribute "productCode"
     */
    public function testPropertyProductCode()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }
}
