<?php
/**
 * SubscriptionProvisioningResponseDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\ProvisionerApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yoast.com provisioning API
 *
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yoast\ProvisionerApiClient;

use PHPUnit\Framework\TestCase;

/**
 * SubscriptionProvisioningResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description SubscriptionProvisioningResponseDto
 * @package     Yoast\ProvisionerApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionProvisioningResponseDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SubscriptionProvisioningResponseDto"
     */
    public function testSubscriptionProvisioningResponseDto()
    {
    }

    /**
     * Test attribute "iD"
     */
    public function testPropertyID()
    {
    }

    /**
     * Test attribute "subscriptionNumber"
     */
    public function testPropertySubscriptionNumber()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "pluginDownloadUrls"
     */
    public function testPropertyPluginDownloadUrls()
    {
    }

    /**
     * Test attribute "siteUrl"
     */
    public function testPropertySiteUrl()
    {
    }
}
