<?php
/**
 * ProvisioningDownloadsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\ProvisionerApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yoast.com provisioning API
 *
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\ProvisionerApiClient;

use Yoast\ProvisionerApiClient\Configuration;
use Yoast\ProvisionerApiClient\ApiException;
use Yoast\ProvisionerApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProvisioningDownloadsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\ProvisionerApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProvisioningDownloadsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for provisioningDownloadsControllerCurrentVersion
     *
     * Retrieve the current version for the productCode for the provisioner..
     *
     */
    public function testProvisioningDownloadsControllerCurrentVersion()
    {
    }

    /**
     * Test case for provisioningDownloadsControllerCurrentVersionV2
     *
     * Get current version of downloads for a product..
     *
     */
    public function testProvisioningDownloadsControllerCurrentVersionV2()
    {
    }

    /**
     * Test case for provisioningDownloadsControllerCurrentZip
     *
     * Redirect to the current zip for the productCode..
     *
     */
    public function testProvisioningDownloadsControllerCurrentZip()
    {
    }
}
