<?php
/**
 * SubscriptionProvisioningApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yoast\ProvisionerApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yoast.com provisioning API
 *
 * The Yoast provisioning API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yoast\ProvisionerApiClient;

use Yoast\ProvisionerApiClient\Configuration;
use Yoast\ProvisionerApiClient\ApiException;
use Yoast\ProvisionerApiClient\ObjectSerializer;

/**
 * SubscriptionProvisioningApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yoast\ProvisionerApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionProvisioningApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiProvisioningSubscriptionsCreatePost
     *
     * Create a subscription.
     *
     */
    public function testApiProvisioningSubscriptionsCreatePost()
    {
    }

    /**
     * Test case for apiProvisioningSubscriptionsIdCancelPost
     *
     * Cancel a single subscription.
     *
     */
    public function testApiProvisioningSubscriptionsIdCancelPost()
    {
    }

    /**
     * Test case for apiProvisioningSubscriptionsIdGet
     *
     * Get a subscription.
     *
     */
    public function testApiProvisioningSubscriptionsIdGet()
    {
    }

    /**
     * Test case for apiProvisioningSubscriptionsIdRefundPost
     *
     * Refund a single subscription.
     *
     */
    public function testApiProvisioningSubscriptionsIdRefundPost()
    {
    }

    /**
     * Test case for apiProvisioningSubscriptionsIdRenewPost
     *
     * Renew a subscription.
     *
     */
    public function testApiProvisioningSubscriptionsIdRenewPost()
    {
    }

    /**
     * Test case for apiProvisioningSubscriptionsIdSetSitePost
     *
     * Link a subscription to a site.
     *
     */
    public function testApiProvisioningSubscriptionsIdSetSitePost()
    {
    }
}
